"use client"
import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
const pjs = Plus_Jakarta_Sans({ subsets: ['latin'] })
import { FooterBar, HeaderBar, LoadingBox } from '../components'
import { Suspense } from 'react'
import Loading from './loading'

export const metadata = {
  title: 'Job Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={pjs.className}>
        <HeaderBar />
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
        <FooterBar />
      </body>
    </html>
  )
}
